import React,{useEffect,useMemo,useState}from'react'
import{Download,RefreshCw,UsersRound}from'lucide-react'
import{supabase}from'../supabase'
import SearchSelect from'../components/SearchSelect'
type R={id:string;data_recebimento:string;valor:number;historico_mensal:boolean;observacoes:string|null;vendas_v17_12:{numero:string;clientes:{nome:string}|null}|null}
const brl=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v||0),hoje=()=>new Date().toISOString().slice(0,10)
export default function RecebimentosClientesV1738(){const[lista,setLista]=useState<R[]>([]),[inicio,setInicio]=useState('2025-01-01'),[fim,setFim]=useState(hoje()),[cliente,setCliente]=useState(''),[loading,setLoading]=useState(true),[erro,setErro]=useState('')
 async function carregar(){setLoading(true);setErro('');const{data,error}=await supabase.from('recebimentos_clientes_v17_36').select('id,data_recebimento,valor,historico_mensal,observacoes,vendas_v17_12(numero,clientes(nome))').eq('cancelado',false).order('data_recebimento',{ascending:false});if(error)setErro('Aplique o SQL V17.37 antes de usar esta tela: '+error.message);else setLista((data||[])as unknown as R[]);setLoading(false)}
 useEffect(()=>{void carregar()},[]);const clientes=useMemo(()=>[...new Set(lista.map(r=>r.vendas_v17_12?.clientes?.nome||'Cliente não identificado'))].sort(),[lista]),filtrada=lista.filter(r=>(!inicio||r.data_recebimento>=inicio)&&(!fim||r.data_recebimento<=fim)&&(!cliente||(r.vendas_v17_12?.clientes?.nome||'Cliente não identificado')===cliente)),total=filtrada.reduce((a,r)=>a+Number(r.valor),0)
 function csv(){const linhas=[['data','cliente','compra','tipo','valor','observacoes'],...filtrada.map(r=>[r.data_recebimento,r.vendas_v17_12?.clientes?.nome||'',r.vendas_v17_12?.numero||'',r.historico_mensal?'Pagamento anterior':'Recebimento',Number(r.valor).toFixed(2),r.observacoes||''])],s='\ufeff'+linhas.map(l=>l.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(';')).join('\r\n'),u=URL.createObjectURL(new Blob([s],{type:'text/csv'})),a=document.createElement('a');a.href=u;a.download='recebimentos_clientes.csv';a.click();URL.revokeObjectURL(u)}
 return <div className="space-y-5"><div className="rounded-[24px] bg-zinc-950 text-white p-6 flex gap-3 items-center"><UsersRound className="text-[#ff70c8]"/><div><p className="text-[10px] uppercase tracking-[.2em] font-black text-[#ff70c8]">Financeiro</p><h1 className="text-2xl font-black">Recebimentos de clientes</h1></div></div>{erro&&<div className="aviso erro">{erro}</div>}<div className="grid sm:grid-cols-2 gap-3"><div className="bg-white border rounded-2xl p-4"><p className="text-[10px] uppercase font-black text-zinc-400">Recebido no período</p><p className="text-2xl font-black text-emerald-700 mt-2">{brl(total)}</p></div><div className="bg-white border rounded-2xl p-4"><p className="text-[10px] uppercase font-black text-zinc-400">Movimentações</p><p className="text-2xl font-black mt-2">{filtrada.length}</p></div></div><div className="bg-white border rounded-[22px] p-4 grid sm:grid-cols-2 lg:grid-cols-4 gap-3"><input type="date" className="input" value={inicio} onChange={e=>setInicio(e.target.value)}/><input type="date" className="input" value={fim} onChange={e=>setFim(e.target.value)}/><SearchSelect value={cliente} onChange={setCliente} options={clientes.map(c=>({value:c,label:c}))} placeholder="Pesquisar cliente..."/><div className="flex gap-2"><button onClick={carregar} className="w-11 h-11 border rounded-xl grid place-items-center"><RefreshCw size={15}/></button><button onClick={csv} className="botao"><Download size={14}/>CSV</button></div></div>{loading?<div className="py-20 grid place-items-center"><RefreshCw className="animate-spin"/></div>:<div className="bg-white border rounded-[22px] overflow-x-auto"><table className="w-full min-w-[800px] text-sm [&_th]:p-3 [&_th]:text-[10px] [&_th]:uppercase [&_td]:p-3 [&_tr]:border-t"><thead><tr><th>Data</th><th>Cliente</th><th>Compra</th><th>Tipo</th><th>Valor</th><th>Observações</th></tr></thead><tbody>{filtrada.map(r=><tr key={r.id}><td className="text-center">{new Date(`${r.data_recebimento}T12:00:00`).toLocaleDateString('pt-BR')}</td><td className="text-center font-bold">{r.vendas_v17_12?.clientes?.nome||'—'}</td><td className="text-center">{r.vendas_v17_12?.numero||'—'}</td><td className="text-center">{r.historico_mensal?'Pagamento anterior':'Recebimento'}</td><td className="text-center font-black text-emerald-700">{brl(Number(r.valor))}</td><td className="text-center">{r.observacoes||'—'}</td></tr>)}</tbody></table></div>}</div>}
