import React,{useEffect,useMemo,useState}from'react'
import{BarChart3,Download,RefreshCw}from'lucide-react'
import{supabase}from'../supabase'
type Aba='entradas'|'saidas'|'estoque'|'movimentacoes';type Linha=Record<string,unknown>;type Col=[string,string,boolean?]
const cfg:Record<Aba,{view:string;date:string;entidade:string;entidadeLabel:string;cols:Col[]}>=
{entradas:{view:'relatorio_entradas_v17_11',date:'data_entrada',entidade:'fornecedor',entidadeLabel:'Fornecedor',cols:[['data_entrada','Data'],['numero_documento','Documento'],['fornecedor','Fornecedor'],['produto_sku','SKU'],['produto','Produto'],['tamanho','Tam.'],['quantidade','Qtd.'],['custo_unitario','Custo',true],['item_total','Total',true]]},saidas:{view:'relatorio_saidas_v17_12',date:'data_venda',entidade:'cliente',entidadeLabel:'Cliente',cols:[['data_venda','Data'],['numero','Venda'],['cliente','Cliente'],['forma_pagamento','Pagamento'],['produto_sku','SKU'],['produto','Produto'],['tamanho','Tam.'],['quantidade','Qtd.'],['preco_unitario','Preço',true],['item_total','Total',true]]},estoque:{view:'relatorio_estoque_v17_11',date:'',entidade:'fornecedor',entidadeLabel:'Fornecedor',cols:[['produto_sku','SKU'],['produto','Produto'],['categoria','Categoria'],['fornecedor','Fornecedor'],['tamanho','Tam.'],['estoque','Atual'],['estoque_minimo','Mínimo'],['custo','Custo',true],['preco','Venda',true]]},movimentacoes:{view:'relatorio_movimentacoes_v17_11',date:'created_at',entidade:'fornecedor',entidadeLabel:'Origem',cols:[['created_at','Data/hora'],['tipo','Tipo'],['numero_documento','Documento'],['fornecedor','Origem'],['produto_sku','SKU'],['produto','Produto'],['tamanho','Tam.'],['quantidade','Qtd.'],['estoque_anterior','Antes'],['estoque_posterior','Depois']]}}
const moeda=(v:unknown)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0)
export default function RelatoriosAdminV121(){
 const[aba,setAba]=useState<Aba>('entradas'),[dados,setDados]=useState<Linha[]>([]),[loading,setLoading]=useState(false),[erro,setErro]=useState('')
 const[inicio,setInicio]=useState(''),[fim,setFim]=useState(''),[busca,setBusca]=useState(''),[entidade,setEntidade]=useState(''),[produto,setProduto]=useState(''),[extra,setExtra]=useState('')
 async function carregar(){setLoading(true);setErro('');const c=cfg[aba],{data,error}=await supabase.from(c.view).select('*').order(c.date||'produto',{ascending:false});if(error)setErro(error.message);else setDados(data||[]);setLoading(false)}
 useEffect(()=>{setInicio('');setFim('');setBusca('');setEntidade('');setProduto('');setExtra('');void carregar()},[aba])
 const entidades=useMemo(()=>[...new Set(dados.map(x=>String(x[cfg[aba].entidade]||'')).filter(Boolean))].sort(),[dados,aba])
 const produtos=useMemo(()=>[...new Set(dados.map(x=>String(x.produto||'')).filter(Boolean))].sort(),[dados])
 const extras=useMemo(()=>{const campo=aba==='saidas'?'forma_pagamento':aba==='estoque'?'categoria':aba==='movimentacoes'?'tipo':'';return campo?[...new Set(dados.map(x=>String(x[campo]||'')).filter(Boolean))].sort():[]},[dados,aba])
 const filtrados=useMemo(()=>{const c=cfg[aba],q=busca.toLocaleLowerCase('pt-BR').trim();return dados.filter(x=>{const d=c.date?String(x[c.date]||'').slice(0,10):'',campoExtra=aba==='saidas'?'forma_pagamento':aba==='estoque'?'categoria':aba==='movimentacoes'?'tipo':'';return(!inicio||!d||d>=inicio)&&(!fim||!d||d<=fim)&&(!entidade||String(x[c.entidade])===entidade)&&(!produto||String(x.produto)===produto)&&(!extra||String(x[campoExtra])===extra)&&(!q||Object.values(x).some(v=>String(v??'').toLocaleLowerCase('pt-BR').includes(q)))})},[dados,aba,inicio,fim,entidade,produto,extra,busca])
 function limpar(){setInicio('');setFim('');setBusca('');setEntidade('');setProduto('');setExtra('')}
 function exportar(){const cols=cfg[aba].cols,esc=(v:unknown)=>`"${String(v??'').replace(/"/g,'""')}"`,csv='\ufeff'+[cols.map(c=>c[1]).join(';'),...filtrados.map(l=>cols.map(c=>esc(l[c[0]])).join(';'))].join('\r\n'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv'})),a=document.createElement('a');a.href=url;a.download=`thita_${aba}_filtrado.csv`;a.click();URL.revokeObjectURL(url)}
 const extraLabel=aba==='saidas'?'Pagamento':aba==='estoque'?'Categoria':aba==='movimentacoes'?'Tipo':'',unidades=filtrados.reduce((a,x)=>a+Math.abs(Number(x.quantidade||0)),0),valor=filtrados.reduce((a,x)=>a+Number(x.item_total||0),0)
 return <div className="space-y-5"><div className="rounded-[24px] bg-zinc-950 text-white p-6 flex gap-3 items-center"><BarChart3 className="text-[#ff70c8]"/><div><p className="text-[10px] uppercase tracking-[.2em] text-[#ff70c8] font-black">Gestão</p><h1 className="text-2xl font-black">Relatórios com filtros</h1></div></div><div className="flex gap-2 overflow-x-auto">{([['entradas','Entradas'],['saidas','Saídas'],['estoque','Estoque atual'],['movimentacoes','Movimentações']]as[Aba,string][]).map(([id,n])=><button key={id} onClick={()=>setAba(id)} className={`h-10 px-4 rounded-xl border text-xs font-black shrink-0 ${aba===id?'bg-[#c80082] text-white border-[#c80082]':'bg-white'}`}>{n}</button>)}</div><div className="bg-white border rounded-[22px] p-4"><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3"><Campo label="Busca geral"><input className="input" value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Documento, SKU, nome..."/></Campo><Campo label={cfg[aba].entidadeLabel}><select className="input" value={entidade} onChange={e=>setEntidade(e.target.value)}><option value="">Todos</option>{entidades.map(x=><option key={x}>{x}</option>)}</select></Campo><Campo label="Produto"><select className="input" value={produto} onChange={e=>setProduto(e.target.value)}><option value="">Todos</option>{produtos.map(x=><option key={x}>{x}</option>)}</select></Campo>{extraLabel?<Campo label={extraLabel}><select className="input" value={extra} onChange={e=>setExtra(e.target.value)}><option value="">Todos</option>{extras.map(x=><option key={x}>{x}</option>)}</select></Campo>:<div/>}<Campo label="Data inicial"><input type="date" className="input" value={inicio} onChange={e=>setInicio(e.target.value)}/></Campo><Campo label="Data final"><input type="date" className="input" value={fim} onChange={e=>setFim(e.target.value)}/></Campo><div className="flex gap-2 items-end"><button onClick={limpar} className="h-11 px-4 rounded-xl border text-xs font-bold">Limpar</button><button onClick={carregar} className="w-11 h-11 rounded-xl border grid place-items-center"><RefreshCw size={16}/></button><button onClick={exportar} className="h-11 px-4 rounded-xl bg-zinc-950 text-white inline-flex gap-2 items-center text-xs font-black"><Download size={15}/>CSV</button></div></div></div>{erro&&<div className="p-3 bg-red-50 border border-red-200 rounded-xl text-red-700 text-xs">{erro}</div>}<div className="grid grid-cols-3 gap-3"><Metrica label="Registros" valor={filtrados.length}/><Metrica label="Unidades" valor={unidades}/><Metrica label="Valor" valor={aba==='entradas'||aba==='saidas'?moeda(valor):'—'}/></div>{loading?<div className="py-20 grid place-items-center"><RefreshCw className="animate-spin"/></div>:<Tabela aba={aba} dados={filtrados}/>}</div>}
function Tabela({aba,dados}:{aba:Aba;dados:Linha[]}){return <div className="bg-white border rounded-[22px] overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="bg-zinc-50 text-[10px] uppercase text-zinc-500"><tr>{cfg[aba].cols.map(c=><th key={c[0]} className="p-3">{c[1]}</th>)}</tr></thead><tbody>{dados.length?dados.map((l,i)=><tr key={i} className="border-t">{cfg[aba].cols.map(c=><td key={c[0]} className="p-3 text-center">{c[2]?moeda(l[c[0]]):c[0]==='created_at'?new Date(String(l[c[0]])).toLocaleString('pt-BR'):c[0].startsWith('data_')?new Date(`${l[c[0]]}T12:00:00`).toLocaleDateString('pt-BR'):String(l[c[0]]??'—')}</td>)}</tr>):<tr><td colSpan={cfg[aba].cols.length} className="p-14 text-center text-zinc-400">Nenhum registro para os filtros selecionados.</td></tr>}</tbody></table></div>}
function Campo({label,children}:{label:string;children:React.ReactNode}){return <label><span className="text-[10px] font-black uppercase text-zinc-500 block mb-1">{label}</span>{children}</label>}function Metrica({label,valor}:{label:string;valor:string|number}){return <div className="bg-white border rounded-2xl p-4"><p className="text-[10px] uppercase font-black text-zinc-400">{label}</p><p className="mt-2 text-xl font-black">{valor}</p></div>}
