import React,{useEffect,useMemo,useState}from'react'
import{ChevronDown,ChevronUp,Download,RefreshCw,ShieldCheck}from'lucide-react'
import{supabase}from'../supabase'

type Registro={id:string;usuario_id:string|null;tabela:string;operacao:string;registro_id:string|null;detalhes:Record<string,unknown>|null;created_at:string}
type Usuario={id:string;nome:string}
type Variante={id:string;tamanho:string;produtos:{nome:string;sku:string|null}|null}
const modulos:Record<string,string>={movimentacoes_estoque_v17_11:'Estoque',vendas_v17_12:'Vendas',produtos:'Produtos',entradas_mercadorias:'Entradas',crediario_parcelas_v17_13:'Crediário',despesas_v17_16:'Financeiro',contas_pagar_v17_17:'Contas a pagar',app_usuarios:'Usuários e permissões',catalogo_config_v17_22:'Aparência do catálogo',banners_catalogo_v17_22:'Banners'}
const acoes:Record<string,string>={INSERT:'Registro criado',UPDATE:'Registro alterado',DELETE:'Registro excluído',ALTERAR_PERMISSOES:'Permissões alteradas'}

export default function AuditoriaAdmin(){
 const[registros,setRegistros]=useState<Registro[]>([]),[usuarios,setUsuarios]=useState<Usuario[]>([]),[variantes,setVariantes]=useState<Variante[]>([])
 const[busca,setBusca]=useState(''),[operacao,setOperacao]=useState('Todas'),[inicio,setInicio]=useState(''),[fim,setFim]=useState(''),[aberto,setAberto]=useState<string|null>(null),[loading,setLoading]=useState(true),[erro,setErro]=useState('')
 async function carregar(){setLoading(true);setErro('');const[a,u,v]=await Promise.all([supabase.from('auditoria_v17_19').select('id,usuario_id,tabela,operacao,registro_id,detalhes,created_at').order('created_at',{ascending:false}).limit(1000),supabase.from('app_usuarios').select('id,nome').order('nome'),supabase.from('produto_variantes').select('id,tamanho,produtos(nome,sku)')]);if(a.error)setErro(a.error.message);else setRegistros((a.data||[])as Registro[]);if(!u.error)setUsuarios((u.data||[])as Usuario[]);if(!v.error)setVariantes((v.data||[])as unknown as Variante[]);setLoading(false)}
 useEffect(()=>{void carregar()},[])
 const nome=(id:string|null)=>usuarios.find(u=>u.id===id)?.nome||(id?'Usuário identificado':'Sistema')
 const produto=(id:unknown)=>{const v=variantes.find(x=>x.id===id);return v?`${v.produtos?.nome||'Produto'}${v.produtos?.sku?` — ${v.produtos.sku}`:''} • ${v.tamanho}`:'Produto/tamanho'}
 function resumo(r:Registro){const d=r.detalhes||{};if(r.tabela==='movimentacoes_estoque_v17_11')return `${String(d.descricao||tipoMov(d.tipo))}: ${produto(d.variante_id)} • ${Math.abs(Number(d.quantidade)||0)} un. • estoque ${d.estoque_anterior??'—'} → ${d.estoque_posterior??'—'}`;if(r.tabela==='vendas_v17_12')return `Venda ${d.numero||''} • ${d.forma_pagamento||'pagamento não informado'} • R$ ${Number(d.total||0).toFixed(2)} • ${status(d.status)}`;if(r.tabela==='produtos')return `${d.nome||'Produto'}${d.sku?` — ${d.sku}`:''}`;if(r.tabela==='entradas_mercadorias')return `Documento ${d.numero_documento||'não informado'} • R$ ${Number(d.total||0).toFixed(2)} • ${status(d.status)}`;if(r.tabela==='crediario_parcelas_v17_13')return `Parcela ${d.parcela_numero||''}/${d.parcelas_total||''} • R$ ${Number(d.valor||0).toFixed(2)} • ${status(d.status)}`;if(r.tabela==='despesas_v17_16')return `${d.descricao||'Despesa'} • R$ ${Number(d.valor||0).toFixed(2)} • ${status(d.status)}`;if(r.tabela==='contas_pagar_v17_17')return `Parcela ${d.parcela_numero||''}/${d.parcelas_total||''} • R$ ${Number(d.valor||0).toFixed(2)} • ${status(d.status)}`;if(r.tabela==='app_usuarios')return `Perfil ${d.role==='admin'?'Administrador':'Operador'} • ${d.ativo===false?'inativo':'ativo'}`;if(r.tabela==='banners_catalogo_v17_22')return `${d.titulo||'Banner'} • ${d.ativo===false?'inativo':'ativo'}`;return 'Alteração registrada pelo sistema.'}
 const filtrados=useMemo(()=>{const q=busca.trim().toLowerCase();return registros.filter(r=>{const dia=r.created_at.slice(0,10),texto=[nome(r.usuario_id),modulos[r.tabela]||r.tabela,acoes[r.operacao]||r.operacao,resumo(r)].join(' ').toLowerCase();return(!inicio||dia>=inicio)&&(!fim||dia<=fim)&&(operacao==='Todas'||r.operacao===operacao)&&(!q||texto.includes(q))})},[registros,usuarios,variantes,busca,operacao,inicio,fim])
 const operacoes=['Todas',...Array.from(new Set(registros.map(r=>r.operacao))).sort()]
 function csv(){const esc=(v:unknown)=>`"${String(v??'').replaceAll('"','""')}"`;const linhas=[['Data','Usuário','Módulo','Ação','Resumo'],...filtrados.map(r=>[new Date(r.created_at).toLocaleString('pt-BR'),nome(r.usuario_id),modulos[r.tabela]||r.tabela,acoes[r.operacao]||r.operacao,resumo(r)])];const blob=new Blob(['\ufeff'+linhas.map(l=>l.map(esc).join(';')).join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='auditoria-thita.csv';a.click();URL.revokeObjectURL(a.href)}
 return <div className="space-y-5"><div className="rounded-[22px] bg-white border p-5"><div className="flex gap-3 items-center"><ShieldCheck className="text-[#c80082]"/><div><h2 className="text-xl font-black">Histórico de Auditoria</h2><p className="text-xs text-zinc-500">Veja quem realizou cada operação e o que foi alterado.</p></div></div></div>{erro&&<div className="aviso erro">{erro}</div>}<div className="bg-white border rounded-[22px] p-4 grid sm:grid-cols-2 lg:grid-cols-5 gap-3"><input className="input" placeholder="Buscar usuário, módulo ou operação" value={busca} onChange={e=>setBusca(e.target.value)}/><select className="input" value={operacao} onChange={e=>setOperacao(e.target.value)}>{operacoes.map(x=><option key={x} value={x}>{x==='Todas'?x:acoes[x]||x}</option>)}</select><input type="date" className="input" value={inicio} onChange={e=>setInicio(e.target.value)}/><input type="date" className="input" value={fim} onChange={e=>setFim(e.target.value)}/><div className="flex gap-2"><button onClick={carregar} className="acao"><RefreshCw size={14}/>Atualizar</button><button onClick={csv} className="botao"><Download size={14}/>CSV</button></div></div><div className="space-y-2">{loading?<div className="py-20 grid place-items-center"><RefreshCw className="animate-spin"/></div>:filtrados.map(r=><div key={r.id} className="bg-white border rounded-2xl overflow-hidden"><div className="p-4 grid md:grid-cols-[150px_160px_150px_1fr_auto] gap-3 items-center text-sm"><div><span className="md:hidden rotulo">Data</span>{new Date(r.created_at).toLocaleString('pt-BR')}</div><div><span className="md:hidden rotulo">Usuário</span><b>{nome(r.usuario_id)}</b></div><div><span className="md:hidden rotulo">Módulo</span>{modulos[r.tabela]||'Sistema'}</div><div><span className="md:hidden rotulo">Operação</span><b>{acoes[r.operacao]||'Operação registrada'}</b><p className="mt-1 text-xs text-zinc-600">{resumo(r)}</p></div><button onClick={()=>setAberto(aberto===r.id?null:r.id)} className="acao">{aberto===r.id?<ChevronUp size={14}/>:<ChevronDown size={14}/>}Detalhes</button></div>{aberto===r.id&&<div className="border-t bg-zinc-50 p-4"><p className="text-xs font-bold text-zinc-600 mb-2">Informações adicionais</p><Detalhes dados={r.detalhes||{}}/></div>}</div>)}{!loading&&!filtrados.length&&<div className="bg-white border rounded-2xl py-16 text-center text-zinc-400">Nenhum registro encontrado.</div>}</div></div>
}
function status(v:unknown){return String(v||'').toLowerCase()==='cancelada'?'Cancelada':String(v||'').toLowerCase()==='paga'?'Paga':String(v||'').toLowerCase()==='ativa'?'Ativa':String(v||'Situação registrada')}
function tipoMov(v:unknown){return v==='entrada'?'Entrada de mercadoria':v==='saida'?'Venda de produto':v==='devolucao'?'Devolução de cliente':'Ajuste de estoque'}
function Detalhes({dados}:{dados:Record<string,unknown>}){const nomes:Record<string,string>={numero:'Número',numero_documento:'Documento',forma_pagamento:'Forma de pagamento',subtotal:'Subtotal',desconto:'Desconto',entrega:'Entrega',total:'Total',status:'Situação',descricao:'Descrição',quantidade:'Quantidade',estoque_anterior:'Estoque anterior',estoque_posterior:'Estoque posterior',custo_unitario:'Custo unitário',titulo:'Título',ativo:'Ativo',role:'Perfil'};const ocultos=['id','created_by','created_at','updated_at','cliente_id','venda_id','entrada_id','variante_id','usuario_id'];const itens=Object.entries(dados).filter(([k,v])=>!ocultos.includes(k)&&v!==null&&v!=='');return <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-2">{itens.map(([k,v])=><div key={k} className="bg-white border rounded-xl p-3"><span className="text-[10px] uppercase font-bold text-zinc-400">{nomes[k]||k.replaceAll('_',' ')}</span><p className="text-sm font-semibold break-words">{typeof v==='object'?JSON.stringify(v):String(v)}</p></div>)}</div>}
