import React,{useEffect,useMemo,useState}from'react'
import{Download,RefreshCw,ShieldCheck}from'lucide-react'
import{supabase}from'../supabase'
type Registro={id:string;usuario_id:string|null;tabela:string;operacao:string;registro_id:string|null;detalhes:Record<string,unknown>|null;created_at:string}
type Usuario={id:string;nome:string}
export default function AuditoriaAdmin(){
 const[registros,setRegistros]=useState<Registro[]>([]),[usuarios,setUsuarios]=useState<Usuario[]>([]),[busca,setBusca]=useState(''),[operacao,setOperacao]=useState('Todas'),[inicio,setInicio]=useState(''),[fim,setFim]=useState(''),[loading,setLoading]=useState(true),[erro,setErro]=useState('')
 async function carregar(){setLoading(true);setErro('');const[a,u]=await Promise.all([supabase.from('auditoria_v17_19').select('id,usuario_id,tabela,operacao,registro_id,detalhes,created_at').order('created_at',{ascending:false}).limit(1000),supabase.from('app_usuarios').select('id,nome').order('nome')]);if(a.error)setErro(a.error.message);else setRegistros((a.data||[])as Registro[]);if(!u.error)setUsuarios((u.data||[])as Usuario[]);setLoading(false)}
 useEffect(()=>{void carregar()},[])
 const nome=(id:string|null)=>usuarios.find(u=>u.id===id)?.nome||(id?'Usuário não identificado':'Sistema')
 const filtrados=useMemo(()=>{const q=busca.trim().toLowerCase();return registros.filter(r=>{const dia=r.created_at.slice(0,10);return(!inicio||dia>=inicio)&&(!fim||dia<=fim)&&(operacao==='Todas'||r.operacao===operacao)&&(!q||[r.tabela,r.operacao,r.registro_id||'',nome(r.usuario_id),JSON.stringify(r.detalhes||{})].some(x=>x.toLowerCase().includes(q)))})},[registros,usuarios,busca,operacao,inicio,fim])
 const operacoes=['Todas',...Array.from(new Set(registros.map(r=>r.operacao))).sort()]
 function csv(){const esc=(v:unknown)=>`"${String(v??'').replaceAll('"','""')}"`;const linhas=[['Data','Usuário','Tabela','Operação','Registro','Detalhes'],...filtrados.map(r=>[new Date(r.created_at).toLocaleString('pt-BR'),nome(r.usuario_id),r.tabela,r.operacao,r.registro_id||'',JSON.stringify(r.detalhes||{})])];const blob=new Blob(['\ufeff'+linhas.map(l=>l.map(esc).join(';')).join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='auditoria-thita.csv';a.click();URL.revokeObjectURL(a.href)}
 return <div className="space-y-5"><div className="rounded-[24px] bg-zinc-950 text-white p-6 flex gap-3"><ShieldCheck className="text-[#ff70c8]"/><div><p className="text-[10px] uppercase tracking-[.2em] font-black text-[#ff70c8]">V17.21</p><h1 className="text-2xl font-black">Auditoria do Sistema</h1><p className="text-xs text-zinc-400">Histórico administrativo disponível somente para administradores.</p></div></div>{erro&&<div className="aviso erro">{erro}</div>}<div className="bg-white border rounded-[22px] p-4 grid sm:grid-cols-2 lg:grid-cols-5 gap-3"><input className="input" placeholder="Buscar usuário, tabela ou registro" value={busca} onChange={e=>setBusca(e.target.value)}/><select className="input" value={operacao} onChange={e=>setOperacao(e.target.value)}>{operacoes.map(x=><option key={x}>{x}</option>)}</select><input type="date" className="input" value={inicio} onChange={e=>setInicio(e.target.value)}/><input type="date" className="input" value={fim} onChange={e=>setFim(e.target.value)}/><div className="flex gap-2"><button onClick={carregar} className="acao"><RefreshCw size={14}/>Atualizar</button><button onClick={csv} className="botao"><Download size={14}/>CSV</button></div></div><div className="bg-white border rounded-[22px] overflow-x-auto">{loading?<div className="py-20 grid place-items-center"><RefreshCw className="animate-spin"/></div>:<table className="w-full min-w-[850px] text-sm"><thead className="bg-zinc-50 text-[10px] uppercase text-zinc-500"><tr><th className="text-left px-5 py-3">Data</th><th>Usuário</th><th>Tabela</th><th>Operação</th><th>Registro</th><th className="text-left">Detalhes</th></tr></thead><tbody>{filtrados.map(r=><tr key={r.id} className="border-t"><td className="px-5 py-3 whitespace-nowrap">{new Date(r.created_at).toLocaleString('pt-BR')}</td><td className="text-center">{nome(r.usuario_id)}</td><td className="text-center">{r.tabela}</td><td className="text-center font-bold">{r.operacao}</td><td className="text-center text-xs">{r.registro_id||'—'}</td><td className="px-3 py-3 text-xs max-w-[320px] break-words">{JSON.stringify(r.detalhes||{})}</td></tr>)}{!filtrados.length&&<tr><td colSpan={6} className="py-16 text-center text-zinc-400">Nenhum registro encontrado.</td></tr>}</tbody></table>}</div></div>
}
