import React,{useState}from'react'
import{Download,Database,ShieldCheck}from'lucide-react'
import{supabase}from'../supabase'

const obrigatorias=['clientes','fornecedores','categorias','produtos','produto_variantes','produto_imagens','entradas_mercadorias','vendas_v17_12','venda_itens_v17_12','crediario_parcelas_v17_13','recebimentos_clientes_v17_36']
const opcionais=['entradas','entrada_rascunho_itens','vendas_rascunhos_v17_28','vendas_rascunho_itens_v17_28','movimentacoes_estoque_v17_11','ajustes_estoque_v17_37','eventos_clientes_v17_36','despesas_v17_16','contas_pagar_v17_17','categorias_financeiras_v17_18','vendedores_v17_30','config_taxas_cartao_v17_31','catalogo_config_v17_22','banners_catalogo_v17_22','app_usuarios','auditoria_v17_19']

async function lerTabela(nome:string){const todos:unknown[]=[];for(let inicio=0;;inicio+=1000){const{data,error}=await supabase.from(nome).select('*').range(inicio,inicio+999);if(error)throw error;const lote=data||[];todos.push(...lote);if(lote.length<1000)break}return todos}
const bytes=(s:string)=>new TextEncoder().encode(s)
async function sha256(s:string){const hash=await crypto.subtle.digest('SHA-256',bytes(s));return[...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,'0')).join('').toUpperCase()}
const momento=()=>new Date().toISOString().replace(/[:.]/g,'-')

export default function BackupCompletoV1747(){const[gerando,setGerando]=useState(false),[progresso,setProgresso]=useState(''),[erro,setErro]=useState(''),[ok,setOk]=useState('')
 async function baixar(){setGerando(true);setErro('');setOk('');try{const tabelas:Record<string,unknown[]>={},indisponiveis:{tabela:string;motivo:string}[]=[];const lista=[...obrigatorias,...opcionais];for(let i=0;i<lista.length;i++){const nome=lista[i];setProgresso(`Copiando ${i+1} de ${lista.length}: ${nome}`);try{tabelas[nome]=await lerTabela(nome)}catch(e){const motivo=e instanceof Error?e.message:String(e);if(obrigatorias.includes(nome))throw new Error(`Não foi possível copiar ${nome}: ${motivo}`);indisponiveis.push({tabela:nome,motivo})}}
  const geradoEm=new Date().toISOString(),dados={formato:'THITA_STORE_BACKUP_COMPLETO',versao:'17.47',gerado_em:geradoEm,tabelas,contagens:Object.fromEntries(Object.entries(tabelas).map(([k,v])=>[k,v.length])),tabelas_opcionais_indisponiveis:indisponiveis,observacao:'Restauração exclusiva pelo suporte. Senhas, chaves secretas e credenciais de autenticação não são exportadas.'};const conteudo=JSON.stringify(dados);const assinatura=await sha256(conteudo);const arquivo=JSON.stringify({manifesto:{formato:'THITA_STORE_BACKUP_COMPLETO',versao:'17.47',gerado_em:geradoEm,sha256_dados:assinatura},dados},null,2);const url=URL.createObjectURL(new Blob([arquivo],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`THITA_STORE_BACKUP_COMPLETO_${momento()}.json`;a.click();URL.revokeObjectURL(url);setOk(`Backup concluído: ${Object.values(tabelas).reduce((a,v)=>a+v.length,0)} registros copiados. Guarde o arquivo em local seguro.`)}catch(e){setErro(e instanceof Error?e.message:'Não foi possível gerar o backup.')}finally{setProgresso('');setGerando(false)}}
 return <div className="space-y-5"><div className="rounded-[24px] bg-zinc-950 text-white p-6 flex gap-3 items-center"><Database className="text-[#ff70c8]"/><div><p className="text-[10px] uppercase tracking-[.2em] font-black text-[#ff70c8]">Segurança dos dados</p><h2 className="text-2xl font-black">Backup completo</h2><p className="text-xs text-zinc-400 mt-1">Clientes, fornecedores, produtos, estoque, vendas, crediário, recebimentos, financeiro e configurações.</p></div></div>{erro&&<div className="aviso erro">{erro}</div>}{ok&&<div className="aviso ok">{ok}</div>}<div className="bg-white border rounded-[22px] p-6 max-w-3xl"><div className="flex gap-3"><ShieldCheck className="text-emerald-600 shrink-0"/><div><h3 className="font-black">Cópia para suporte</h3><p className="text-sm text-zinc-500 mt-1">O arquivo baixado reúne os dados do sistema e possui uma assinatura de conferência. Caso seja necessário restaurá-lo, envie-o ao suporte.</p><p className="text-xs text-zinc-400 mt-3">Por segurança, senhas e chaves de acesso nunca são incluídas.</p></div></div><button type="button" disabled={gerando} onClick={baixar} className="botao mt-6"><Download size={16}/>{gerando?(progresso||'Gerando backup...'):'Baixar backup completo'}</button></div></div>}
