import React,{useEffect,useMemo,useState}from'react'
import{Check,RefreshCw,RotateCcw,WalletCards}from'lucide-react'
import{supabase}from'../supabase'
import SearchSelect from'../components/SearchSelect'
type P={id:string;parcela_numero:number;parcelas_total:number;vencimento:string;valor:number;status:string;data_pagamento:string|null;ignorar_caixa:boolean;entradas_mercadorias:{numero_documento:string;forma_pagamento:string;fornecedores:{nome:string}|null}|null;despesas_v17_16:{descricao:string;categoria:string;forma_pagamento:string}|null}
const brl=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0),hoje=()=>new Date().toISOString().slice(0,10)
export default function ContasPagarAdmin(){
 const[dados,setDados]=useState<P[]>([]),[status,setStatus]=useState('aberta'),[origem,setOrigem]=useState(''),[inicio,setInicio]=useState(''),[fim,setFim]=useState(''),[loading,setLoading]=useState(true),[erro,setErro]=useState(''),[ok,setOk]=useState('')
 async function carregar(){setLoading(true);setErro('');const{data,error}=await supabase.from('contas_pagar_v17_17').select('id,parcela_numero,parcelas_total,vencimento,valor,status,data_pagamento,ignorar_caixa,entradas_mercadorias(numero_documento,forma_pagamento,fornecedores(nome)),despesas_v17_16(descricao,categoria,forma_pagamento)').order('vencimento');if(error)setErro(error.message);else setDados(((data||[])as unknown as P[]).filter(x=>!x.ignorar_caixa));setLoading(false)}
 useEffect(()=>{void carregar()},[])
 const origens=useMemo(()=>[...new Set(dados.map(x=>x.entradas_mercadorias?.fornecedores?.nome||x.despesas_v17_16?.categoria||'').filter(Boolean))].sort(),[dados]),lista=dados.filter(x=>(!status||x.status===status)&&(!origem||(x.entradas_mercadorias?.fornecedores?.nome||x.despesas_v17_16?.categoria)===origem)&&(!inicio||x.vencimento>=inicio)&&(!fim||x.vencimento<=fim)),totalPesquisa=lista.reduce((a,x)=>a+Number(x.valor),0)
 async function acao(rpc:string,id:string,msg:string){const{error}=await supabase.rpc(rpc,rpc==='pagar_conta_v17_17'?{p_id:id,p_data:hoje()}:{p_id:id});if(error)setErro(error.message);else{setOk(msg);await carregar()}}
 return <div className="space-y-5"><div className="rounded-[24px] bg-zinc-950 text-white p-6 flex gap-3"><WalletCards className="text-[#ff70c8]"/><h1 className="text-2xl font-black">Contas a Pagar</h1></div>{erro&&<div className="aviso erro">{erro}</div>}{ok&&<div className="aviso ok">{ok}</div>}<div className="grid sm:grid-cols-2"><div className="bg-white border rounded-2xl p-4"><p className="text-[10px] uppercase font-black text-zinc-400">Total da pesquisa</p><p className="mt-2 text-xl font-black">{brl(totalPesquisa)}</p></div></div><div className="bg-white border rounded-[22px] p-4 grid sm:grid-cols-2 lg:grid-cols-[180px_1fr_180px_180px_auto] gap-3"><select className="input" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todas</option><option value="aberta">Abertas</option><option value="paga">Pagas</option><option value="cancelada">Canceladas</option></select><SearchSelect value={origem} onChange={setOrigem} options={origens.map(x=>({value:x,label:x}))} placeholder="Pesquisar fornecedor ou categoria..."/><input type="date" title="Data inicial" className="input" value={inicio} onChange={e=>setInicio(e.target.value)}/><input type="date" title="Data final" className="input" value={fim} onChange={e=>setFim(e.target.value)}/><button onClick={carregar} className="w-11 h-11 border rounded-xl grid place-items-center"><RefreshCw size={15}/></button></div>{loading?<div className="py-20 grid place-items-center"><RefreshCw className="animate-spin"/></div>:<div className="bg-white border rounded-[22px] overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead><tr><th>Vencimento</th><th>Origem</th><th>Documento/descrição</th><th>Parcela</th><th>Pagamento</th><th>Valor</th><th>Situação</th><th></th></tr></thead><tbody>{lista.map(x=>{const ent=x.entradas_mercadorias,des=x.despesas_v17_16;return <tr key={x.id} className="border-t"><td>{new Date(x.vencimento+'T12:00:00').toLocaleDateString('pt-BR')}</td><td>{ent?.fornecedores?.nome||des?.categoria}</td><td>{ent?.numero_documento||des?.descricao}</td><td>{x.parcela_numero}/{x.parcelas_total}</td><td>{ent?.forma_pagamento||des?.forma_pagamento}</td><td className="font-black">{brl(x.valor)}</td><td className={x.status==='aberta'&&x.vencimento<hoje()?'text-red-600 font-black':''}>{x.status==='aberta'&&x.vencimento<hoje()?'VENCIDA':x.status.toUpperCase()}</td><td>{x.status==='aberta'&&<button className="acao" onClick={()=>acao('pagar_conta_v17_17',x.id,'Pagamento registrado.')}><Check size={13}/>Pagar hoje</button>}{x.status==='paga'&&<button className="acao" onClick={()=>acao('desfazer_pagamento_conta_v17_17',x.id,'Pagamento desfeito.')}><RotateCcw size={13}/>Desfazer</button>}</td></tr>})}</tbody><tfoot><tr className="bg-zinc-950 text-white font-black"><td colSpan={5} className="p-3 text-right">TOTAL DA PESQUISA ({lista.length})</td><td className="text-center">{brl(totalPesquisa)}</td><td colSpan={2}/></tr></tfoot></table></div>}</div>
}
