import React,{useEffect,useMemo,useState}from'react'
import{CheckCircle,RefreshCw,RotateCcw,WalletCards,X}from'lucide-react'
import{supabase}from'../supabase'
type Parcela={id:string;venda_id:string;numero_venda:string;cliente:string;parcela_numero:number;parcelas_total:number;vencimento:string;valor:number;status:string;data_pagamento:string|null}
const hoje=()=>new Date().toISOString().slice(0,10)
export default function CrediarioAdmin(){
 const[lista,setLista]=useState<Parcela[]>([]),[status,setStatus]=useState('aberta'),[cliente,setCliente]=useState(''),[loading,setLoading]=useState(true),[erro,setErro]=useState(''),[ok,setOk]=useState(''),[receber,setReceber]=useState<Parcela|null>(null),[valor,setValor]=useState(''),[dataRecebimento,setDataRecebimento]=useState(hoje()),[salvando,setSalvando]=useState(false)
 async function carregar(){setLoading(true);const{data,error}=await supabase.from('relatorio_crediario_v17_13').select('*').order('vencimento');if(error)setErro(error.message);else setLista((data||[])as Parcela[]);setLoading(false)}
 useEffect(()=>{void carregar()},[])
 const clientes=useMemo(()=>[...new Set(lista.map(x=>x.cliente))].sort(),[lista]),dia=hoje(),filtrada=lista.filter(p=>(!cliente||p.cliente===cliente)&&(status==='todas'||status==='vencida'?(p.status==='aberta'&&p.vencimento<dia):p.status===status)),aberto=lista.filter(p=>p.status==='aberta').reduce((a,p)=>a+Number(p.valor),0),vencido=lista.filter(p=>p.status==='aberta'&&p.vencimento<dia).reduce((a,p)=>a+Number(p.valor),0)
 function abrirRecebimento(p:Parcela){setReceber(p);setValor(Number(p.valor).toFixed(2));setDataRecebimento(hoje());setErro('');setOk('')}
 async function confirmar(){if(!receber)return;const recebido=Number(valor.replace(',','.'));if(!Number.isFinite(recebido)||recebido<=0){setErro('Informe um valor recebido maior que zero.');return}if(!dataRecebimento){setErro('Informe a data do recebimento.');return}setSalvando(true);setErro('');const{error}=await supabase.rpc('receber_parcela_crediario_v17_29',{p_parcela_id:receber.id,p_valor_recebido:recebido,p_data_recebimento:dataRecebimento});if(error)setErro(error.message);else{setOk('Recebimento registrado com o valor e a data informados.');setReceber(null);await carregar()}setSalvando(false)}
 async function desfazer(p:Parcela){setErro('');setOk('');const{error}=await supabase.rpc('desfazer_recebimento_crediario_v17_29',{p_parcela_id:p.id});if(error)setErro(error.message);else{setOk('Pagamento desfeito.');await carregar()}}
 return <div className="space-y-5"><div className="rounded-[24px] bg-zinc-950 text-white p-6 flex items-center gap-3"><WalletCards className="text-[#ff70c8]"/><div><p className="text-[10px] uppercase tracking-[.2em] text-[#ff70c8] font-black">Financeiro</p><h1 className="text-2xl font-black">Crediário</h1></div></div>{erro&&<div className="aviso erro">{erro}</div>}{ok&&<div className="aviso ok">{ok}</div>}<div className="grid grid-cols-3 gap-3"><Card label="Em aberto" valor={`R$ ${aberto.toFixed(2)}`}/><Card label="Vencido" valor={`R$ ${vencido.toFixed(2)}`}/><Card label="Parcelas abertas" valor={lista.filter(p=>p.status==='aberta').length}/></div><div className="bg-white border rounded-[22px] p-4 flex flex-wrap gap-3"><select className="input max-w-52" value={status} onChange={e=>setStatus(e.target.value)}><option value="aberta">Em aberto</option><option value="vencida">Vencidas</option><option value="paga">Pagas</option><option value="todas">Todas</option></select><select className="input max-w-64" value={cliente} onChange={e=>setCliente(e.target.value)}><option value="">Todos os clientes</option>{clientes.map(c=><option key={c}>{c}</option>)}</select><button onClick={carregar} className="w-11 h-11 rounded-xl border grid place-items-center"><RefreshCw size={16}/></button></div>{loading?<div className="py-20 grid place-items-center"><RefreshCw className="animate-spin"/></div>:<div className="bg-white border rounded-[22px] overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead className="bg-zinc-50 text-[10px] uppercase text-zinc-500"><tr><th className="p-3 text-left">Venda</th><th>Cliente</th><th>Parcela</th><th>Vencimento</th><th>Valor</th><th>Status</th><th></th></tr></thead><tbody>{filtrada.map(p=>{const atrasada=p.status==='aberta'&&p.vencimento<dia;return <tr key={p.id} className="border-t"><td className="p-3 font-bold">{p.numero_venda}</td><td className="text-center">{p.cliente}</td><td className="text-center">{p.parcela_numero}/{p.parcelas_total}</td><td className={`text-center font-bold ${atrasada?'text-red-600':''}`}>{new Date(`${p.vencimento}T12:00:00`).toLocaleDateString('pt-BR')}</td><td className="text-center font-black">R$ {Number(p.valor).toFixed(2)}</td><td className="text-center"><span className={`px-2 py-1 rounded-full text-[10px] font-black ${p.status==='paga'?'bg-emerald-50 text-emerald-700':atrasada?'bg-red-50 text-red-700':'bg-amber-50 text-amber-700'}`}>{p.status==='paga'?'PAGA':atrasada?'VENCIDA':'ABERTA'}</span></td><td className="pr-4"><button onClick={()=>p.status==='paga'?void desfazer(p):abrirRecebimento(p)} className="h-9 px-3 rounded-lg border text-xs font-bold inline-flex gap-2 items-center">{p.status==='paga'?<RotateCcw size={14}/>:<CheckCircle size={14}/>} {p.status==='paga'?'Desfazer':'Receber'}</button></td></tr>})}</tbody></table></div>}
 {receber&&<div className="fixed inset-0 z-[140] bg-black/55 p-4 grid place-items-center" onClick={()=>setReceber(null)}><div className="bg-white rounded-[24px] p-6 w-full max-w-md" onClick={e=>e.stopPropagation()}><div className="flex justify-between"><div><h2 className="text-xl font-black">Receber parcela</h2><p className="text-xs text-zinc-500 mt-1">Venda {receber.numero_venda} • {receber.cliente}</p></div><button onClick={()=>setReceber(null)}><X/></button></div><div className="mt-5 space-y-3"><label><span className="text-xs font-bold block mb-1">Valor recebido (R$)</span><input autoFocus type="number" min="0.01" step="0.01" className="input" value={valor} onChange={e=>setValor(e.target.value)}/></label><label><span className="text-xs font-bold block mb-1">Data do recebimento</span><input type="date" className="input" value={dataRecebimento} onChange={e=>setDataRecebimento(e.target.value)}/></label></div><div className="mt-5 flex justify-end gap-2"><button disabled={salvando} onClick={()=>setReceber(null)} className="h-11 px-4 rounded-xl border font-bold">Cancelar</button><button disabled={salvando} onClick={confirmar} className="h-11 px-5 rounded-xl bg-[#c80082] text-white font-black">{salvando?'Registrando...':'Confirmar recebimento'}</button></div></div></div>}
 </div>
}
function Card({label,valor}:{label:string;valor:string|number}){return <div className="bg-white border rounded-2xl p-4"><p className="text-[10px] uppercase font-black text-zinc-400">{label}</p><p className="mt-2 text-xl font-black">{valor}</p></div>}
