import React,{useEffect,useMemo,useState} from 'react'
import {Check,PackagePlus,Plus,RefreshCw,Trash2} from 'lucide-react'
import {supabase} from '../supabase'

type Fornecedor={id:string;nome:string}
type Variante={id:string;tamanho:string;estoque:number;ativo:boolean}
type Produto={id:string;nome:string;sku:string|null;custo:number;produto_variantes:Variante[]}
type Item={variante_id:string;produto:string;tamanho:string;quantidade:number;custo_unitario:number}
type Entrada={id:string;numero_documento:string;data_entrada:string;total:number;frete:number;forma_pagamento:string|null;parcelas_pagamento:number;fornecedores:{nome:string}|null}

export default function EntradasAdmin(){
 const [fornecedores,setFornecedores]=useState<Fornecedor[]>([]),[produtos,setProdutos]=useState<Produto[]>([]),[entradas,setEntradas]=useState<Entrada[]>([]),[itens,setItens]=useState<Item[]>([])
 const [fornecedorId,setFornecedorId]=useState(''),[numero,setNumero]=useState(''),[data,setData]=useState(new Date().toISOString().slice(0,10)),[frete,setFrete]=useState(0),[forma,setForma]=useState(''),[parcelas,setParcelas]=useState(1),[primeiroVencimento,setPrimeiroVencimento]=useState(''),[obs,setObs]=useState('')
 const [produtoId,setProdutoId]=useState(''),[varianteId,setVarianteId]=useState(''),[qtd,setQtd]=useState(1),[custo,setCusto]=useState(0),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[erro,setErro]=useState(''),[ok,setOk]=useState('')
 const parcelado=forma==='Cartão de Crédito'||forma==='Boleto'
 async function carregar(){setLoading(true);const [f,p,e]=await Promise.all([supabase.from('fornecedores').select('id,nome').eq('ativo',true).order('nome'),supabase.from('produtos').select('id,nome,sku,custo,produto_variantes(id,tamanho,estoque,ativo)').eq('ativo',true).order('nome'),supabase.from('entradas_mercadorias').select('id,numero_documento,data_entrada,total,frete,forma_pagamento,parcelas_pagamento,fornecedores(nome)').order('created_at',{ascending:false}).limit(30)]);if(f.error||p.error||e.error)setErro(f.error?.message||p.error?.message||e.error?.message||'Erro ao carregar.');else{setFornecedores(f.data||[]);setProdutos((p.data||[]) as Produto[]);setEntradas((e.data||[]) as unknown as Entrada[])}setLoading(false)}
 useEffect(()=>{void carregar()},[])
 const produto=useMemo(()=>produtos.find(p=>p.id===produtoId),[produtos,produtoId]),variantes=(produto?.produto_variantes||[]).filter(v=>v.ativo)
 function selecionarProduto(id:string){setProdutoId(id);const p=produtos.find(x=>x.id===id);setVarianteId('');setCusto(Number(p?.custo)||0)}
 function adicionar(){setErro('');const p=produtos.find(x=>x.id===produtoId),v=p?.produto_variantes.find(x=>x.id===varianteId);if(!p||!v){setErro('Selecione produto e tamanho.');return}if(qtd<=0||custo<0){setErro('Informe quantidade e custo válidos.');return}setItens(prev=>{const existente=prev.find(i=>i.variante_id===v.id);return existente?prev.map(i=>i.variante_id===v.id?{...i,quantidade:i.quantidade+qtd,custo_unitario:custo}:i):[...prev,{variante_id:v.id,produto:p.nome,tamanho:v.tamanho,quantidade:qtd,custo_unitario:custo}]});setVarianteId('');setQtd(1)}
 const subtotal=itens.reduce((a,i)=>a+i.quantidade*i.custo_unitario,0),total=subtotal+frete
 async function salvar(e:React.FormEvent){e.preventDefault();setErro('');setOk('');setSaving(true);try{if(!fornecedorId)throw new Error('Selecione o fornecedor.');if(!numero.trim())throw new Error('Informe o número da nota/documento.');if(!data)throw new Error('Informe a data da entrada.');if(!forma)throw new Error('Selecione a forma de pagamento.');if(parcelado&&!primeiroVencimento)throw new Error('Informe o primeiro vencimento.');if(!itens.length)throw new Error('Adicione pelo menos um item.');const {error}=await supabase.rpc('registrar_entrada_v17_17',{p_fornecedor_id:fornecedorId,p_numero_documento:numero.trim(),p_data_entrada:data,p_frete:Number(frete)||0,p_observacoes:obs.trim()||null,p_forma_pagamento:forma,p_parcelas_pagamento:parcelado?parcelas:1,p_primeiro_vencimento:parcelado?primeiroVencimento:null,p_itens:itens.map(i=>({variante_id:i.variante_id,quantidade:i.quantidade,custo_unitario:i.custo_unitario}))});if(error)throw error;setOk(parcelado?'Entrada registrada e parcelas geradas em Contas a Pagar.':'Entrada registrada e pagamento lançado no Financeiro.');setItens([]);setNumero('');setFrete(0);setForma('');setParcelas(1);setPrimeiroVencimento('');setObs('');await carregar()}catch(e){setErro(e instanceof Error?e.message:'Não foi possível registrar a entrada.')}finally{setSaving(false)}}
 return <div className="space-y-5">
  <form onSubmit={salvar} className="bg-white border border-zinc-200 rounded-[22px] p-5 md:p-6">
   <div className="flex items-center gap-3"><div className="w-11 h-11 rounded-xl bg-[#fff0f8] text-[#c80082] grid place-items-center"><PackagePlus size={20}/></div><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#c80082]">Estoque e Financeiro</p><h2 className="text-xl font-black">Nova entrada de mercadorias</h2></div></div>
   {erro&&<Aviso erro>{erro}</Aviso>}{ok&&<Aviso>{ok}</Aviso>}
   <div className="grid md:grid-cols-4 gap-3 mt-5">
    <Campo label="Fornecedor *"><select className="input" value={fornecedorId} onChange={e=>setFornecedorId(e.target.value)}><option value="">Selecione</option>{fornecedores.map(f=><option key={f.id} value={f.id}>{f.nome}</option>)}</select></Campo>
    <Campo label="Nº nota/documento *"><input className="input" value={numero} onChange={e=>setNumero(e.target.value)}/></Campo>
    <Campo label="Data *"><input type="date" className="input" value={data} onChange={e=>setData(e.target.value)}/></Campo>
    <Campo label="Frete (R$)"><input type="number" min="0" step=".01" className="input" value={frete} onChange={e=>setFrete(Number(e.target.value))}/></Campo>
    <Campo label="Forma de pagamento *"><select className="input" value={forma} onChange={e=>{setForma(e.target.value);setParcelas(1)}}><option value="">Selecione</option>{['Pix','Transferência','Cartão de Débito','Cartão de Crédito','Boleto'].map(x=><option key={x}>{x}</option>)}</select></Campo>
    {parcelado&&<Campo label="Quantidade de parcelas *"><select className="input" value={parcelas} onChange={e=>setParcelas(Number(e.target.value))}>{Array.from({length:24},(_,i)=>i+1).map(x=><option key={x} value={x}>{x}x</option>)}</select></Campo>}
    {parcelado&&<Campo label="Primeiro vencimento *"><input type="date" className="input" value={primeiroVencimento} onChange={e=>setPrimeiroVencimento(e.target.value)}/></Campo>}
   </div>
   <div className="mt-5 rounded-2xl bg-zinc-50 border p-4"><p className="text-xs font-black mb-3">Adicionar produtos e tamanhos</p><div className="grid md:grid-cols-[2fr_1fr_100px_130px_auto] gap-2"><select className="input" value={produtoId} onChange={e=>selecionarProduto(e.target.value)}><option value="">Produto</option>{produtos.map(p=><option key={p.id} value={p.id}>{p.nome} — {p.sku}</option>)}</select><select className="input" value={varianteId} onChange={e=>setVarianteId(e.target.value)}><option value="">Tamanho</option>{variantes.map(v=><option key={v.id} value={v.id}>{v.tamanho} (atual {v.estoque})</option>)}</select><input type="number" min="1" className="input" value={qtd} onChange={e=>setQtd(Number(e.target.value))}/><input type="number" min="0" step=".01" className="input" value={custo} onChange={e=>setCusto(Number(e.target.value))}/><button type="button" onClick={adicionar} className="h-11 px-4 rounded-xl bg-zinc-950 text-white grid place-items-center"><Plus size={17}/></button></div>
   {itens.length>0&&<div className="overflow-x-auto mt-4"><table className="w-full min-w-[620px] text-sm"><thead className="text-[10px] uppercase text-zinc-500"><tr><th className="text-left py-2">Produto</th><th>Tam.</th><th>Qtd.</th><th>Custo</th><th>Total</th><th></th></tr></thead><tbody>{itens.map(i=><tr key={i.variante_id} className="border-t"><td className="py-2 font-bold">{i.produto}</td><td className="text-center">{i.tamanho}</td><td className="text-center">{i.quantidade}</td><td className="text-center">R$ {i.custo_unitario.toFixed(2)}</td><td className="text-center font-bold">R$ {(i.quantidade*i.custo_unitario).toFixed(2)}</td><td><button type="button" onClick={()=>setItens(x=>x.filter(y=>y.variante_id!==i.variante_id))} className="text-red-600"><Trash2 size={14}/></button></td></tr>)}</tbody></table></div>}</div>
   <Campo label="Observações"><textarea className="input min-h-20 py-3" value={obs} onChange={e=>setObs(e.target.value)}/></Campo><div className="mt-5 flex flex-col sm:flex-row justify-between gap-3 items-end"><div className="text-sm text-zinc-500"><p>Itens: <b>{itens.length}</b></p><p>Subtotal: <b>R$ {subtotal.toFixed(2)}</b></p><p className="text-lg text-zinc-900">Total da compra: <b>R$ {total.toFixed(2)}</b></p>{parcelado&&<p className="text-xs">Serão geradas {parcelas} parcelas em Contas a Pagar.</p>}</div><button disabled={saving} className="h-12 px-6 rounded-xl bg-[#c80082] text-white font-black text-sm inline-flex items-center gap-2"><Check size={16}/>{saving?'Registrando...':'Confirmar entrada'}</button></div>
  </form>
  <div className="bg-white border rounded-[22px] overflow-hidden"><div className="p-5 flex justify-between"><div><h2 className="font-black">Entradas recentes</h2><p className="text-xs text-zinc-500">Cada entrada confirmada também aparece como saída no Financeiro.</p></div><button onClick={carregar} className="w-10 h-10 rounded-xl border grid place-items-center"><RefreshCw size={16}/></button></div>{loading?<div className="py-12 grid place-items-center"><RefreshCw className="animate-spin"/></div>:<div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-zinc-50 text-[10px] uppercase text-zinc-500"><tr><th className="text-left px-5 py-3">Documento</th><th>Data</th><th>Fornecedor</th><th>Pagamento</th><th>Frete</th><th>Total</th></tr></thead><tbody>{entradas.map(e=><tr key={e.id} className="border-t"><td className="px-5 py-3 font-bold">{e.numero_documento}</td><td className="text-center">{new Date(`${e.data_entrada}T12:00:00`).toLocaleDateString('pt-BR')}</td><td className="text-center">{e.fornecedores?.nome||'—'}</td><td className="text-center">{e.forma_pagamento||'—'}{Number(e.parcelas_pagamento)>1?` (${e.parcelas_pagamento}x)`:''}</td><td className="text-center">R$ {Number(e.frete).toFixed(2)}</td><td className="text-center font-black">R$ {Number(e.total).toFixed(2)}</td></tr>)}</tbody></table></div>}</div>
 </div>
}
function Campo({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="text-[11px] font-bold text-zinc-600 block mb-1.5">{label}</span>{children}</label>}
function Aviso({children,erro=false}:{children:React.ReactNode;erro?:boolean}){return <div className={`mt-4 rounded-xl border p-3 text-xs font-semibold ${erro?'border-red-200 bg-red-50 text-red-700':'border-emerald-200 bg-emerald-50 text-emerald-700'}`}>{children}</div>}
