import React, { useEffect, useMemo, useState } from 'react'
import { BarChart3, Download, Eye, RefreshCw, X } from 'lucide-react'
import { supabase } from '../supabase'

type Aba = 'entradas'|'saidas'|'estoque'|'movimentacoes'
type Linha = Record<string, unknown>
type Grupo = { id:string; data:string; numero:string; entidade:string; qtd:number; total:number; desconto:number }
const brl=(v:unknown)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0)
const dataBR=(v:string)=>new Date(`${v.slice(0,10)}T12:00:00`).toLocaleDateString('pt-BR')

export default function RelatoriosAdminV152(){
  const [aba,setAba]=useState<Aba>('entradas'),[dados,setDados]=useState<Linha[]>([]),[descontos,setDescontos]=useState<Record<string,number>>({})
  const [inicio,setInicio]=useState(''),[fim,setFim]=useState(''),[entidade,setEntidade]=useState(''),[produto,setProduto]=useState(''),[operacao,setOperacao]=useState(''),[busca,setBusca]=useState('')
  const [aberto,setAberto]=useState<Grupo|null>(null),[loading,setLoading]=useState(true),[erro,setErro]=useState('')
  const view=aba==='entradas'?'relatorio_entradas_v17_11':aba==='saidas'?'relatorio_saidas_v17_12':aba==='estoque'?'relatorio_estoque_v17_11':'relatorio_movimentacoes_v17_11'
  async function carregar(){setLoading(true);setErro('');const rel=await supabase.from(view).select('*');if(rel.error)setErro(rel.error.message);else setDados(rel.data||[]);if(aba==='saidas'){const vendas=await supabase.from('vendas_v17_12').select('id,desconto');if(vendas.error)setErro(vendas.error.message);else setDescontos(Object.fromEntries((vendas.data||[]).map(v=>[String(v.id),Number(v.desconto)||0])))}else setDescontos({});setLoading(false)}
  useEffect(()=>{setInicio('');setFim('');setEntidade('');setProduto('');setOperacao('');setBusca('');setAberto(null);void carregar()},[aba])
  const campoEntidade=aba==='saidas'?'cliente':'fornecedor',campoData=aba==='entradas'?'data_entrada':aba==='saidas'?'data_venda':aba==='movimentacoes'?'created_at':''
  const entidades=useMemo(()=>[...new Set(dados.map(x=>String(x[campoEntidade]||'')).filter(Boolean))].sort(),[dados,campoEntidade])
  const produtos=useMemo(()=>[...new Set(dados.map(x=>String(x.produto||'')).filter(Boolean))].sort(),[dados])
  const operacoes=useMemo(()=>[...new Set(dados.map(x=>String(x.descricao_movimentacao||'')).filter(Boolean))].sort(),[dados])
  const filtrados=useMemo(()=>{const q=busca.toLowerCase().trim();return dados.filter(x=>{const d=campoData?String(x[campoData]||'').slice(0,10):'';return(!inicio||!d||d>=inicio)&&(!fim||!d||d<=fim)&&(!entidade||String(x[campoEntidade])===entidade)&&(!produto||String(x.produto)===produto)&&(!operacao||String(x.descricao_movimentacao)===operacao)&&(!q||Object.values(x).some(v=>String(v??'').toLowerCase().includes(q)))})},[dados,inicio,fim,entidade,produto,operacao,busca,campoData,campoEntidade])
  const grupos=useMemo(()=>{const mapa=new Map<string,Grupo>();if(!['entradas','saidas'].includes(aba))return[];for(const x of filtrados){const id=String(x[aba==='entradas'?'entrada_id':'venda_id']),existente=mapa.get(id);if(existente)existente.qtd+=Number(x.quantidade);else mapa.set(id,{id,data:String(x[aba==='entradas'?'data_entrada':'data_venda']),numero:String(x[aba==='entradas'?'numero_documento':'numero']),entidade:String(x[campoEntidade]),qtd:Number(x.quantidade),total:Number(x[aba==='entradas'?'entrada_total':'venda_total']),desconto:aba==='saidas'?Number(descontos[id]||0):Number(x.desconto_nota||0)})}return[...mapa.values()]},[filtrados,aba,campoEntidade,descontos])
  const detalhe=aberto?dados.filter(x=>String(x[aba==='entradas'?'entrada_id':'venda_id'])===aberto.id):[]
  const historico=aberto&&aba==='saidas'?grupos.filter(g=>g.entidade===aberto.entidade):[]
  const resumo=historico.reduce((a,g)=>({vendas:a.vendas+1,qtd:a.qtd+g.qtd,total:a.total+g.total,desconto:a.desconto+g.desconto}),{vendas:0,qtd:0,total:0,desconto:0})
  function csv(){const cols=Object.keys(filtrados[0]||{}),esc=(v:unknown)=>`"${String(v??'').replace(/"/g,'""')}"`,texto='\ufeff'+[cols.join(';'),...filtrados.map(x=>cols.map(c=>esc(x[c])).join(';'))].join('\r\n'),url=URL.createObjectURL(new Blob([texto],{type:'text/csv'})),a=document.createElement('a');a.href=url;a.download=`thita_${aba}.csv`;a.click();URL.revokeObjectURL(url)}
  return <div className="space-y-5">
    <div className="rounded-[24px] bg-zinc-950 text-white p-6 flex gap-3"><BarChart3 className="text-[#ff70c8]"/><h1 className="text-2xl font-black">Relatórios</h1></div>
    <div className="flex gap-2">{(['entradas','saidas','estoque','movimentacoes'] as Aba[]).map(a=><button key={a} onClick={()=>setAba(a)} className={`h-10 px-4 rounded-xl border capitalize text-xs font-black ${aba===a?'bg-[#c80082] text-white':'bg-white'}`}>{a}</button>)}</div>
    <div className="bg-white border rounded-[22px] p-4 grid sm:grid-cols-2 lg:grid-cols-4 gap-3"><Campo label="Busca geral"><input className="input" value={busca} onChange={e=>setBusca(e.target.value)}/></Campo><Campo label={aba==='saidas'?'Cliente':'Fornecedor/origem'}><select className="input" value={entidade} onChange={e=>setEntidade(e.target.value)}><option value="">Todos</option>{entidades.map(x=><option key={x}>{x}</option>)}</select></Campo><Campo label="Produto"><select className="input" value={produto} onChange={e=>setProduto(e.target.value)}><option value="">Todos</option>{produtos.map(x=><option key={x}>{x}</option>)}</select></Campo>{aba==='movimentacoes'?<Campo label="Operação realizada"><select className="input" value={operacao} onChange={e=>setOperacao(e.target.value)}><option value="">Todas</option>{operacoes.map(x=><option key={x}>{x}</option>)}</select></Campo>:<div/>}<Campo label="Data inicial"><input type="date" className="input" value={inicio} onChange={e=>setInicio(e.target.value)}/></Campo><Campo label="Data final"><input type="date" className="input" value={fim} onChange={e=>setFim(e.target.value)}/></Campo><div className="flex gap-2 items-end"><button onClick={carregar} className="w-11 h-11 border rounded-xl grid place-items-center"><RefreshCw size={15}/></button><button onClick={csv} className="botao"><Download size={14}/>CSV</button></div></div>
    {erro&&<div className="aviso erro">{erro}</div>}{loading?<div className="py-20 grid place-items-center"><RefreshCw className="animate-spin"/></div>:aba==='entradas'||aba==='saidas'?<Resumo grupos={grupos} aba={aba} abrir={setAberto}/>:<Detalhes dados={filtrados} movimentacoes={aba==='movimentacoes'}/>} 
    {aberto&&<div className="fixed inset-0 z-[120] bg-black/55 p-4 grid place-items-center" onClick={()=>setAberto(null)}><div className="bg-white rounded-[24px] max-w-5xl w-full max-h-[90vh] overflow-auto" onClick={e=>e.stopPropagation()}><div className="p-5 flex justify-between border-b"><div><h2 className="font-black text-xl">{aba==='saidas'?`Histórico de ${aberto.entidade}`:`${aberto.numero} • ${aberto.entidade}`}</h2>{aba==='saidas'?<><p className="text-sm font-bold mt-1">{resumo.vendas} venda(s) • {resumo.qtd} un. • {brl(resumo.total)}</p><p className="text-xs text-[#c80082] font-bold">Descontos concedidos: {brl(resumo.desconto)}</p><p className="text-xs text-zinc-500 mt-2">Venda {aberto.numero}: {dataBR(aberto.data)} • {aberto.qtd} un. • {brl(aberto.total)} • Desconto {brl(aberto.desconto)}</p></>:<p className="text-xs text-zinc-500">{dataBR(aberto.data)} • {aberto.qtd} un. • {brl(aberto.total)}</p>}</div><button onClick={()=>setAberto(null)}><X/></button></div><table className="w-full"><thead><tr><th>SKU</th><th>Produto</th><th>Tam.</th><th>Qtd.</th><th>Unitário</th><th>Total</th></tr></thead><tbody>{detalhe.map((x,i)=><tr key={i}><td>{String(x.produto_sku)}</td><td>{String(x.produto)}</td><td>{String(x.tamanho)}</td><td>{String(x.quantidade)}</td><td>{brl(x[aba==='entradas'?'custo_unitario':'preco_unitario'])}</td><td>{brl(x.item_total)}</td></tr>)}</tbody></table></div></div>}
  </div>
}
function Resumo({grupos,aba,abrir}:{grupos:Grupo[];aba:Aba;abrir:(g:Grupo)=>void}){return <Tabela><table><thead><tr><th>Data</th><th>Documento</th><th>{aba==='saidas'?'Cliente':'Fornecedor'}</th><th>Unidades</th>{aba==='saidas'&&<th>Desconto</th>}<th>Total</th><th></th></tr></thead><tbody>{grupos.map(g=><tr key={g.id}><td>{dataBR(g.data)}</td><td>{g.numero}</td><td>{g.entidade}</td><td>{g.qtd}</td>{aba==='saidas'&&<td>{brl(g.desconto)}</td>}<td>{brl(g.total)}</td><td><button className="acao" onClick={()=>abrir(g)}><Eye size={14}/>Abrir histórico</button></td></tr>)}</tbody></table></Tabela>}
function Detalhes({dados,movimentacoes}:{dados:Linha[];movimentacoes:boolean}){return <Tabela><table><thead><tr>{movimentacoes?<><th>Data</th><th>Operação realizada</th><th>Produto</th><th>Tam.</th><th>Qtd.</th><th>Antes</th><th>Depois</th></>:<><th>SKU</th><th>Produto</th><th>Fornecedor</th><th>Tam.</th><th>Atual</th><th>Mínimo</th></>}</tr></thead><tbody>{dados.map((x,i)=><tr key={i}>{movimentacoes?<><td>{new Date(String(x.created_at)).toLocaleString('pt-BR')}</td><td>{String(x.descricao_movimentacao)}</td><td>{String(x.produto)}</td><td>{String(x.tamanho)}</td><td>{String(x.quantidade)}</td><td>{String(x.estoque_anterior)}</td><td>{String(x.estoque_posterior)}</td></>:<><td>{String(x.produto_sku)}</td><td>{String(x.produto)}</td><td>{String(x.fornecedor)}</td><td>{String(x.tamanho)}</td><td>{String(x.estoque)}</td><td>{String(x.estoque_minimo)}</td></>}</tr>)}</tbody></table></Tabela>}
function Campo({label,children}:{label:string;children:React.ReactNode}){return <label><span className="text-[10px] uppercase font-black text-zinc-500 block mb-1">{label}</span>{children}</label>}
function Tabela({children}:{children:React.ReactNode}){return <div className="bg-white border rounded-[22px] overflow-x-auto"><style>{`table{width:100%;min-width:800px}th{padding:12px;font-size:10px;text-transform:uppercase;background:#fafafa}td{padding:12px;text-align:center;border-top:1px solid #eee}`}</style>{children}</div>}
