import React, { useEffect, useMemo, useState } from 'react'
import { BarChart3, Download, Eye, RefreshCw, X } from 'lucide-react'
import { supabase } from '../supabase'

type Aba = 'entradas'|'saidas'|'estoque'|'movimentacoes'|'recebimentos'
type Linha = Record<string, unknown>
type Grupo = { id:string; data:string; numero:string; entidade:string; qtd:number; total:number; desconto:number }
type Recebimento = {id:string;data:string;documento:string;cliente:string;forma:string;origem:string;valor:number}
const brl=(v:unknown)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0)
const dataBR=(v:string)=>new Date(`${v.slice(0,10)}T12:00:00`).toLocaleDateString('pt-BR')

export default function RelatoriosAdminV152(){
  const [aba,setAba]=useState<Aba>('entradas'),[dados,setDados]=useState<Linha[]>([]),[descontos,setDescontos]=useState<Record<string,number>>({})
  const [inicio,setInicio]=useState(''),[fim,setFim]=useState(''),[entidade,setEntidade]=useState(''),[produto,setProduto]=useState(''),[operacao,setOperacao]=useState(''),[busca,setBusca]=useState('')
  const [recebimentos,setRecebimentos]=useState<Recebimento[]>([]),[formaRecebimento,setFormaRecebimento]=useState('')
  const [aberto,setAberto]=useState<Grupo|null>(null),[loading,setLoading]=useState(true),[erro,setErro]=useState('')
  const view=aba==='entradas'?'relatorio_entradas_v17_11':aba==='saidas'?'relatorio_saidas_v17_12':aba==='estoque'?'relatorio_estoque_v17_11':'relatorio_movimentacoes_v17_11'
  async function lerTudo(tabela:string,ordem:string,ascendente:boolean){const todos:Linha[]=[];for(let inicio=0;;inicio+=1000){const rel=await supabase.from(tabela).select('*').order(ordem,{ascending:ascendente}).range(inicio,inicio+999);if(rel.error)throw rel.error;const lote=(rel.data||[])as Linha[];todos.push(...lote);if(lote.length<1000)break}return todos}
  async function acrescentarRecebimentosLegados(){const parcelas:Linha[]=[];for(let i=0;;i+=1000){const r=await supabase.from('crediario_parcelas_v17_13').select('id,venda_id,data_pagamento,vencimento,valor,valor_recebido,status,ignorar_caixa,vendas_v17_12(numero,status,clientes(nome))').eq('status','paga').order('data_pagamento',{ascending:false}).range(i,i+999);if(r.error)throw r.error;parcelas.push(...(r.data||[])as Linha[]);if((r.data||[]).length<1000)break}const ativos:Linha[]=[];for(let i=0;;i+=1000){const r=await supabase.from('recebimentos_clientes_v17_36').select('parcela_id').eq('cancelado',false).not('parcela_id','is',null).range(i,i+999);if(r.error)throw r.error;ativos.push(...(r.data||[])as Linha[]);if((r.data||[]).length<1000)break}const vinculadas=new Set(ativos.map(r=>String(r.parcela_id)));const legados:Recebimento[]=parcelas.filter(p=>!p.ignorar_caixa&&!vinculadas.has(String(p.id))).map(p=>{const v=p.vendas_v17_12 as {numero?:string;status?:string;clientes?:{nome?:string}}|null;return{id:`legado-${p.id}`,data:String(p.data_pagamento||p.vencimento),documento:v?.numero||'—',cliente:v?.clientes?.nome||'—',forma:'Crediário',origem:'Pagamento anterior',valor:Number(p.valor_recebido||p.valor)||0}}).filter(r=>r.valor>0);setRecebimentos(atual=>[...atual,...legados].sort((a,b)=>b.data.localeCompare(a.data)||b.id.localeCompare(a.id)))}
  async function carregarRecebimentos(){const vendas:Linha[]=[];for(let i=0;;i+=1000){const r=await supabase.from('vendas_v17_12').select('id,numero,data_venda,forma_pagamento,total,status,clientes(nome)').order('data_venda',{ascending:false}).range(i,i+999);if(r.error)throw r.error;vendas.push(...(r.data||[])as Linha[]);if((r.data||[]).length<1000)break}const pagamentos:Linha[]=[];for(let i=0;;i+=1000){const r=await supabase.from('recebimentos_clientes_v17_36').select('id,venda_id,data_recebimento,valor,cancelado,vendas_v17_12(numero,status,clientes(nome))').order('data_recebimento',{ascending:false}).range(i,i+999);if(r.error)throw r.error;pagamentos.push(...(r.data||[])as Linha[]);if((r.data||[]).length<1000)break}const imediatos=vendas.filter(v=>v.status!=='cancelada'&&String(v.forma_pagamento).toLocaleLowerCase('pt-BR')!=='crediário').map(v=>{const c=v.clientes as {nome?:string}|null;return{id:`v-${v.id}`,data:String(v.data_venda),documento:String(v.numero),cliente:c?.nome||'—',forma:String(v.forma_pagamento||'Não informada'),origem:'Venda',valor:Number(v.total)||0}});const crediario=pagamentos.filter(r=>!r.cancelado).map(r=>{const v=r.vendas_v17_12 as {numero?:string;status?:string;clientes?:{nome?:string}}|null;return{id:`r-${r.id}`,data:String(r.data_recebimento),documento:v?.numero||'—',cliente:v?.clientes?.nome||'—',forma:'Crediário',origem:'Recebimento',valor:Number(r.valor)||0}}).filter(r=>r.valor>0);setRecebimentos([...imediatos,...crediario].sort((a,b)=>b.data.localeCompare(a.data)||b.id.localeCompare(a.id)))}
  async function carregar(){setLoading(true);setErro('');try{if(aba==='recebimentos'){await carregarRecebimentos();await acrescentarRecebimentosLegados();setDados([]);setDescontos({});return}const ordem=aba==='saidas'?'numero':aba==='entradas'?'numero_documento':aba==='movimentacoes'?'created_at':'produto';setDados(await lerTudo(view,ordem,aba==='saidas'||aba==='estoque'));if(aba==='saidas'){const vendas=await lerTudo('vendas_v17_12','created_at',true);setDescontos(Object.fromEntries(vendas.map(v=>[String(v.id),Number(v.desconto)||0])))}else if(aba==='entradas'){const entradas=await lerTudo('entradas_mercadorias','created_at',true);setDescontos(Object.fromEntries(entradas.map(v=>[String(v.id),Number(v.desconto_nota)||0])))}else setDescontos({})}catch(e){setErro(e instanceof Error?e.message:'Não foi possível carregar todos os registros.')}finally{setLoading(false)}}
  useEffect(()=>{setInicio('');setFim('');setEntidade('');setProduto('');setOperacao('');setBusca('');setFormaRecebimento('');setAberto(null);void carregar()},[aba])
  const campoEntidade=aba==='saidas'?'cliente':'fornecedor',campoData=aba==='entradas'?'data_entrada':aba==='saidas'?'data_venda':aba==='movimentacoes'?'created_at':''
  const entidades=useMemo(()=>[...new Set(dados.map(x=>String(x[campoEntidade]||'')).filter(Boolean))].sort(),[dados,campoEntidade])
  const produtos=useMemo(()=>[...new Set(dados.map(x=>String(x.produto||'')).filter(Boolean))].sort(),[dados])
  const operacoes=useMemo(()=>[...new Set(dados.map(x=>String(x.descricao_movimentacao||'')).filter(Boolean))].sort(),[dados])
  const filtrados=useMemo(()=>{const q=busca.toLowerCase().trim();return dados.filter(x=>{const d=campoData?String(x[campoData]||'').slice(0,10):'';return(!inicio||!d||d>=inicio)&&(!fim||!d||d<=fim)&&(!entidade||String(x[campoEntidade])===entidade)&&(!produto||String(x.produto)===produto)&&(!operacao||String(x.descricao_movimentacao)===operacao)&&(!q||Object.values(x).some(v=>String(v??'').toLowerCase().includes(q)))})},[dados,inicio,fim,entidade,produto,operacao,busca,campoData,campoEntidade])
  const grupos=useMemo(()=>{const mapa=new Map<string,Grupo>();if(!['entradas','saidas'].includes(aba))return[];for(const x of filtrados){const id=String(x[aba==='entradas'?'entrada_id':'venda_id']),existente=mapa.get(id);if(existente)existente.qtd+=Number(x.quantidade);else mapa.set(id,{id,data:String(x[aba==='entradas'?'data_entrada':'data_venda']),numero:String(x[aba==='entradas'?'numero_documento':'numero']),entidade:String(x[campoEntidade]),qtd:Number(x.quantidade),total:Number(x[aba==='entradas'?'entrada_total':'venda_total']),desconto:Number(descontos[id]||0)})}return[...mapa.values()]},[filtrados,aba,campoEntidade,descontos])
  const gruposExibidos=useMemo(()=>{const q=busca.trim().toLocaleLowerCase('pt-BR');if(!q)return grupos;return grupos.filter(g=>[g.numero,g.entidade,g.data].some(v=>String(v).toLocaleLowerCase('pt-BR').includes(q)))},[grupos,busca])
  const detalhe=aberto?dados.filter(x=>String(x[aba==='entradas'?'entrada_id':'venda_id'])===aberto.id):[]
  const historico=aberto&&aba==='saidas'?grupos.filter(g=>g.entidade===aberto.entidade):[]
  const resumo=historico.reduce((a,g)=>({vendas:a.vendas+1,qtd:a.qtd+g.qtd,total:a.total+g.total,desconto:a.desconto+g.desconto}),{vendas:0,qtd:0,total:0,desconto:0})
  const formasRecebimento=useMemo(()=>[...new Set(recebimentos.map(r=>r.forma))].sort(),[recebimentos])
  const recebimentosFiltrados=useMemo(()=>{const q=busca.trim().toLocaleLowerCase('pt-BR');return recebimentos.filter(r=>(!inicio||r.data>=inicio)&&(!fim||r.data<=fim)&&(!formaRecebimento||r.forma===formaRecebimento)&&(!q||`${r.documento} ${r.cliente} ${r.forma} ${r.origem}`.toLocaleLowerCase('pt-BR').includes(q)))},[recebimentos,inicio,fim,formaRecebimento,busca])
  function csv(){const cols=Object.keys(filtrados[0]||{}),esc=(v:unknown)=>`"${String(v??'').replace(/"/g,'""')}"`,texto='\ufeff'+[cols.join(';'),...filtrados.map(x=>cols.map(c=>esc(x[c])).join(';'))].join('\r\n'),url=URL.createObjectURL(new Blob([texto],{type:'text/csv'})),a=document.createElement('a');a.href=url;a.download=`thita_${aba}.csv`;a.click();URL.revokeObjectURL(url)}
  return <div className="space-y-5">
    <div className="rounded-[24px] bg-zinc-950 text-white p-6 flex gap-3"><BarChart3 className="text-[#ff70c8]"/><h1 className="text-2xl font-black">Relatórios</h1></div>
    <div className="flex gap-2 flex-wrap">{(['entradas','saidas','estoque','movimentacoes','recebimentos'] as Aba[]).map(a=><button key={a} onClick={()=>setAba(a)} className={`h-10 px-4 rounded-xl border capitalize text-xs font-black ${aba===a?'bg-[#c80082] text-white':'bg-white'}`}>{a}</button>)}</div>
    <div className="bg-white border rounded-[22px] p-4 grid sm:grid-cols-2 lg:grid-cols-4 gap-3"><Campo label="Busca geral"><input className="input" value={busca} onChange={e=>setBusca(e.target.value)}/></Campo>{aba==='recebimentos'?<Campo label="Forma de recebimento"><select className="input" value={formaRecebimento} onChange={e=>setFormaRecebimento(e.target.value)}><option value="">Todas</option>{formasRecebimento.map(x=><option key={x}>{x}</option>)}</select></Campo>:<><Campo label={aba==='saidas'?'Cliente':'Fornecedor/origem'}><select className="input" value={entidade} onChange={e=>setEntidade(e.target.value)}><option value="">Todos</option>{entidades.map(x=><option key={x}>{x}</option>)}</select></Campo><Campo label="Produto"><select className="input" value={produto} onChange={e=>setProduto(e.target.value)}><option value="">Todos</option>{produtos.map(x=><option key={x}>{x}</option>)}</select></Campo></>}{aba==='movimentacoes'?<Campo label="Operação realizada"><select className="input" value={operacao} onChange={e=>setOperacao(e.target.value)}><option value="">Todas</option>{operacoes.map(x=><option key={x}>{x}</option>)}</select></Campo>:<div/>}<Campo label="Data inicial"><input type="date" className="input" value={inicio} onChange={e=>setInicio(e.target.value)}/></Campo><Campo label="Data final"><input type="date" className="input" value={fim} onChange={e=>setFim(e.target.value)}/></Campo><div className="flex gap-2 items-end"><button onClick={carregar} className="w-11 h-11 border rounded-xl grid place-items-center"><RefreshCw size={15}/></button>{aba!=='recebimentos'&&<button onClick={csv} className="botao"><Download size={14}/>CSV</button>}</div></div>
    {erro&&<div className="aviso erro">{erro}</div>}{loading?<div className="py-20 grid place-items-center"><RefreshCw className="animate-spin"/></div>:aba==='recebimentos'?<TabelaRecebimentos dados={recebimentosFiltrados}/>:aba==='entradas'||aba==='saidas'?<Resumo grupos={gruposExibidos} aba={aba} abrir={setAberto}/>:<Detalhes dados={filtrados} movimentacoes={aba==='movimentacoes'}/>} 
    {aberto&&<div className="fixed inset-0 z-[120] bg-black/55 p-4 grid place-items-center" onClick={()=>setAberto(null)}><div className="bg-white rounded-[24px] max-w-5xl w-full max-h-[90vh] overflow-auto" onClick={e=>e.stopPropagation()}><div className="p-5 flex justify-between border-b"><div><h2 className="font-black text-xl">{aba==='saidas'?`Histórico de ${aberto.entidade}`:`${aberto.numero} • ${aberto.entidade}`}</h2>{aba==='saidas'?<><p className="text-sm font-bold mt-1">{resumo.vendas} venda(s) • {resumo.qtd} un. • {brl(resumo.total)}</p><p className="text-xs text-[#c80082] font-bold">Descontos concedidos: {brl(resumo.desconto)}</p><p className="text-xs text-zinc-500 mt-2">Venda {aberto.numero}: {dataBR(aberto.data)} • {aberto.qtd} un. • {brl(aberto.total)} • Desconto {brl(aberto.desconto)}</p></>:<p className="text-xs text-zinc-500">{dataBR(aberto.data)} • {aberto.qtd} un. • {brl(aberto.total)}</p>}</div><button onClick={()=>setAberto(null)}><X/></button></div><table className="w-full"><thead><tr><th>SKU</th><th>Produto</th><th>Tam.</th><th>Qtd.</th><th>Unitário</th><th>Total</th></tr></thead><tbody>{detalhe.map((x,i)=><tr key={i}><td>{String(x.produto_sku)}</td><td>{String(x.produto)}</td><td>{String(x.tamanho)}</td><td>{String(x.quantidade)}</td><td>{brl(x[aba==='entradas'?'custo_unitario':'preco_unitario'])}</td><td>{brl(x.item_total)}</td></tr>)}</tbody></table></div></div>}
  </div>
}
function TabelaRecebimentos({dados}:{dados:Recebimento[]}){const[pagina,setPagina]=useState(1),porPagina=50,totalPaginas=Math.max(1,Math.ceil(dados.length/porPagina));useEffect(()=>setPagina(1),[dados]);const atual=Math.min(pagina,totalPaginas),visiveis=dados.slice((atual-1)*porPagina,atual*porPagina),total=dados.reduce((a,r)=>a+r.valor,0);return <><div className="grid sm:grid-cols-2 gap-3 mb-4"><div className="bg-white border rounded-2xl p-5"><p className="text-[10px] uppercase font-black text-zinc-400">Total recebido na pesquisa</p><p className="text-2xl font-black text-emerald-700 mt-2">{brl(total)}</p></div><div className="bg-white border rounded-2xl p-5"><p className="text-[10px] uppercase font-black text-zinc-400">Recebimentos</p><p className="text-2xl font-black mt-2">{dados.length}</p></div></div><Tabela><table><thead><tr><th>Data</th><th>Documento</th><th>Cliente</th><th>Forma</th><th>Origem</th><th>Valor recebido</th></tr></thead><tbody>{visiveis.map(r=><tr key={r.id}><td>{dataBR(r.data)}</td><td>{r.documento}</td><td>{r.cliente}</td><td>{r.forma}</td><td>{r.origem}</td><td className="font-black text-emerald-700">{brl(r.valor)}</td></tr>)}</tbody><tfoot><tr className="bg-zinc-950 text-white font-black"><td colSpan={5} className="text-right">TOTAL DA PESQUISA ({dados.length} registros)</td><td>{brl(total)}</td></tr></tfoot></table></Tabela><Paginacao pagina={atual} total={totalPaginas} registros={dados.length} mudar={setPagina}/></>}
function Resumo({grupos,aba,abrir}:{grupos:Grupo[];aba:Aba;abrir:(g:Grupo)=>void}){const[pagina,setPagina]=useState(1),porPagina=50,totalPaginas=Math.max(1,Math.ceil(grupos.length/porPagina));useEffect(()=>setPagina(1),[grupos]);const paginaAtual=Math.min(pagina,totalPaginas),visiveis=grupos.slice((paginaAtual-1)*porPagina,paginaAtual*porPagina),totais=grupos.reduce((a,g)=>({qtd:a.qtd+g.qtd,desconto:a.desconto+g.desconto,total:a.total+g.total}),{qtd:0,desconto:0,total:0});return <><Tabela><table><thead><tr><th>Data</th><th>Documento</th><th>{aba==='saidas'?'Cliente':'Fornecedor'}</th><th>Unidades</th><th>Desconto</th><th>Total</th><th></th></tr></thead><tbody>{visiveis.map(g=><tr key={g.id}><td>{dataBR(g.data)}</td><td>{g.numero}</td><td>{g.entidade}</td><td>{g.qtd}</td><td>{brl(g.desconto)}</td><td>{brl(g.total)}</td><td><button className="acao" onClick={()=>abrir(g)}><Eye size={14}/>Abrir histórico</button></td></tr>)}</tbody><tfoot><tr className="bg-zinc-950 text-white font-black"><td colSpan={3} className="text-right">SOMA TOTAL ({grupos.length} registros)</td><td>{totais.qtd}</td><td>{brl(totais.desconto)}</td><td>{brl(totais.total)}</td><td></td></tr></tfoot></table></Tabela><Paginacao pagina={paginaAtual} total={totalPaginas} registros={grupos.length} mudar={setPagina}/></>}
function Detalhes({dados,movimentacoes}:{dados:Linha[];movimentacoes:boolean}){const[pagina,setPagina]=useState(1),porPagina=50,totalPaginas=Math.max(1,Math.ceil(dados.length/porPagina));useEffect(()=>setPagina(1),[dados]);const paginaAtual=Math.min(pagina,totalPaginas),visiveis=dados.slice((paginaAtual-1)*porPagina,paginaAtual*porPagina),soma=dados.reduce((a,x)=>a+Number(x[movimentacoes?'quantidade':'estoque']||0),0);return <><Tabela><table><thead><tr>{movimentacoes?<><th>Data</th><th>Operação realizada</th><th>Produto</th><th>Tam.</th><th>Qtd.</th><th>Antes</th><th>Depois</th></>:<><th>SKU</th><th>Produto</th><th>Fornecedor</th><th>Tam.</th><th>Atual</th><th>Mínimo</th></>}</tr></thead><tbody>{visiveis.map((x,i)=><tr key={(paginaAtual-1)*porPagina+i}>{movimentacoes?<><td>{new Date(String(x.created_at)).toLocaleString('pt-BR')}</td><td>{String(x.descricao_movimentacao)}</td><td>{String(x.produto)}</td><td>{String(x.tamanho)}</td><td>{String(x.quantidade)}</td><td>{String(x.estoque_anterior)}</td><td>{String(x.estoque_posterior)}</td></>:<><td>{String(x.produto_sku)}</td><td>{String(x.produto)}</td><td>{String(x.fornecedor)}</td><td>{String(x.tamanho)}</td><td>{String(x.estoque)}</td><td>{String(x.estoque_minimo)}</td></>}</tr>)}</tbody><tfoot><tr className="bg-zinc-950 text-white font-black"><td colSpan={4} className="text-right">SOMA TOTAL ({dados.length} registros)</td><td>{soma}</td><td colSpan={movimentacoes?2:1}></td></tr></tfoot></table></Tabela><Paginacao pagina={paginaAtual} total={totalPaginas} registros={dados.length} mudar={setPagina}/></>}
function Paginacao({pagina,total,registros,mudar}:{pagina:number;total:number;registros:number;mudar:(n:number)=>void}){return <div className="mt-3 bg-white border rounded-2xl p-3 flex flex-wrap justify-between items-center gap-3 text-sm"><span><b>{registros}</b> registro(s) • 50 por página</span><div className="flex items-center gap-2"><button disabled={pagina<=1} onClick={()=>mudar(pagina-1)} className="h-9 px-4 rounded-lg border font-bold disabled:opacity-40">Anterior</button><b>Página {pagina} de {total}</b><button disabled={pagina>=total} onClick={()=>mudar(pagina+1)} className="h-9 px-4 rounded-lg border font-bold disabled:opacity-40">Próxima</button></div></div>}
function Campo({label,children}:{label:string;children:React.ReactNode}){return <label><span className="text-[10px] uppercase font-black text-zinc-500 block mb-1">{label}</span>{children}</label>}
function Tabela({children}:{children:React.ReactNode}){return <div className="bg-white border rounded-[22px] overflow-x-auto"><style>{`table{width:100%;min-width:800px}th{padding:12px;font-size:10px;text-transform:uppercase;background:#fafafa}td{padding:12px;text-align:center;border-top:1px solid #eee}`}</style>{children}</div>}
